### ISSUE TITLE
Type definitions not properly loaded when importing from jest's setupTests

### ISSUE THREAD

**Issue by gnapse** [gnapse/jest-dom#45]
* `jest-dom` version: 1.10.0
* `node` version: 8.11.3
* `react-testing-library` version: 4.1.4

### Relevant code or config:

```js
// package.json
  "jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/src/setupTests.ts",
  },

// src/setupTests.ts
import 'jest-dom/extend-expect';

// src/components/SomeComponent/SomeComponent.test.ts
expect(element).toHaveTextContent('Hello World!');
// TypeScript error in the line above:
// Property 'toHaveTextContent' does not exist on type 'Matchers<void>'
```

### Problem description:

When importing `jest-dom/extend-expect`, as instructed in [the README](https://github.com/gnapse/jest-dom#usage), within jest's `setupTestFrameworkScriptFile` file, and using TypeScript at the same time, I get TypeScript errors in my test files saying that this library's custom matchers are not found:

```
Property 'toHaveTextContent' does not exist on type 'Matchers<void>'
```

However, when I import `jest-dom/extend-expect` from within the very text files that need those matchers it all works. Moreover, it even works if I import it in just one of those files, which suddenly removes the TS warning from a second test file, without having to import it again from that second test file.

### Suggested solution:

[This StackOverflow answer](https://stackoverflow.com/a/43674912/621809) may be part of the solution, but I wanted to bring this up first to see if someone more knowledgeable with TypeScript can help. @jgoz maybe?

**Comment by jgoz** [comment]
It would be helpful to see the `tsconfig.json` file too, but my guess would be that `setupTests.ts` is not being included as a source file in the TypeScript config when compiling the tests, which means TypeScript would never see the `import` statement and would therefore not augment the `jest` namespace. It would also explain why adding the import to a single test file fixes it (since the namespace only needs to be augmented once).

I can think of a couple possible solutions:
1. Make sure `setupTests.ts` is in the `files` or `include` section of your `tsconfig.json` file
2. Add a `.d.ts` file to your project (like `jest-dom.d.ts`), making sure it's included in the `files` or `include` section, that looks like the following:

    ```ts
    import "jest-dom/extend-expect";
    ```
    (This is what I do in my projects.)

You can try either one of the above - no need to do both.

**Comment by gnapse** [comment]
Thanks! Your tips got me in the right direction. I did not even have to add the file to the includes, but rather remove it from the excludes. Turns out `create-react-app-typescript`'s default configuration excludes it, as you can see [here](https://github.com/wmonk/create-react-app-typescript/blob/e4b1f9424fa14f7aae7f0cbf5fd64e18dd273527/packages/react-scripts/template/tsconfig.json#L28). I wonder why they do that? Should I file an issue with them?

Anyway, thanks again. I'm closing this.

**Comment by jgoz** [comment]
Great!

It looks like excluding that file was deliberate: https://github.com/wmonk/create-react-app-typescript/commit/8e24948ce2a06148fd8e229c6b356a62d7ab83dc

It should probably be handled in the [`tsconfig.test.json`](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/tsconfig.test.json) file (which I assume is used for tests), but it would involve duplicating the `exclude` config from `tsconfig.json` due to the rules around `extends` and `include`, `exclude`:

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs"
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "webpack"
  ]
}
```

**Comment by gnapse** [comment]
Hmmm, but when I do that, vscode still flags me the error. And not just vscode, but CRA's `npm run start` as well:

```
Failed to compile.

/Users/ernesto/code/mck/org-admin/src/lib/api/__tests__/Query.tsx
(45,21): Property 'toHaveTextContent' does not exist on type 'Matchers<void>'.
```

BTW I nevertheless opened the ticket wmonk/create-react-app-typescript#371 though your response does clarify a bit about the why. I'll try your second method and see how it goes.

**Comment by jgoz** [comment]
Maybe the `tsconfig.test.json` file is not actually being used when executing the tests. Does this use `ts-jest`?

**Comment by gnapse** [comment]
Wouldn't know. I'm using [create-react-app-typescript](
https://github.com/wmonk/create-react-app-typescript) and this is my first TypeScript project ever. I'll continue digging and hopefully also someone in that ticket will respond.

**Comment by Darep** [comment]
For anyone else wondering here: We were having this problem mainly with VSCode. Project ran tests fine without warnings. Creating a `src/@types/jest-dom.d.ts` with:

```javascript
import "jest-dom/extend-expect";
```

"fixed" it for us :)

**Comment by FullStackForger** [comment]
I started with what @Darep did but it looks like there is no need for creating separate `@types` folder.
To make it work I added below into `globals.d.ts` and it seems to fix the problem. 
> ```js
> import "jest-dom/extend-expect";
> ```

@Darep What's your reasoning behind `@types` folder?

**Comment by randallagordon** [comment]
The issue for us turned out to be that the setup file was still a `.js` instead of `.ts`! 😅

**Comment by MoeSauber** [comment]
I still have problems, even though[ my `setupTests` file is `.ts`](https://github.com/MoeSauber/change/blob/master/src/setupTests.ts). I still ge errors liket:
> error TS2304: Cannot find name 'afterAll'.
> error TS2339: Property 'toBeInTheDocument' does not exist on type 'Assertion'.

https://travis-ci.org/MoeSauber/change/builds/570179189#L363-L397

**Comment by gnapse** [comment]
> error TS2304: Cannot find name 'afterAll'.

`afterAll` is not provided by `jest-dom` but by `jest` itself. So it looks like you've got deeper issues with TS+jest and not just with jest-dom.

**Comment by MuYunyun** [comment]
> It would be helpful to see the `tsconfig.json` file too, but my guess would be that `setupTests.ts` is not being included as a source file in the TypeScript config when compiling the tests, which means TypeScript would never see the `import` statement and would therefore not augment the `jest` namespace. It would also explain why adding the import to a single test file fixes it (since the namespace only needs to be augmented once).
> 
> I can think of a couple possible solutions:
> 
> 1. Make sure `setupTests.ts` is in the `files` or `include` section of your `tsconfig.json` file
> 2. Add a `.d.ts` file to your project (like `jest-dom.d.ts`), making sure it's included in the `files` or `include` section, that looks like the following:
>    ```ts
>    import "jest-dom/extend-expect";
>    ```
>    
>    
>    (This is what I do in my projects.)
> 
> You can try either one of the above - no need to do both.

My solve is to define a file called "scripts/setupEnv.d.ts", and include it in `tsconfig.json` file, it seems it can pass the test case, however the api of `@testing-library/jest-dom/extend-expect` is still in red.

![image](https://user-images.githubusercontent.com/19354791/75225778-3a464600-57e6-11ea-9fd3-19d79d66ada9.png)

**Comment by kirill-konshin** [comment]
Maybe this would help:

```js
import '@testing-library/jest-dom/extend-expect';
```

**Comment by mulili** [comment]
add a file named 'jest-dom-d.ts' in src/@types include
`import '@testing-library/jest-dom/extend-expect';`

**Comment by jamiehaywood** [comment]
> Maybe this would help:
> 
> ```js
> import '@testing-library/jest-dom/extend-expect';
> ```
> 
> Also add `@types/testing-library__jest-dom` to dependencies of your project.

@kirill-konshin THANK YOU! I added this at the top of my test file, and it fixed the issue.

**Comment by xaun** [comment]
I have a `setupTests.ts` configured with jest.config `setupFilesAfterEnv` with `import '@testing-library/jest-dom/extend-expect'`. 

I needed to add `"testing-library__jest-dom"` to my tsconfig.json `"types"` option to fix the `Property 'toBeInTheDocument' does not exist on type 'Matchers<HTMLElement>` type warning for my vscode intellisense.

Can someone explain why it needed to be registered here when the types fall within my default rootTypes (`node_modules/@types/`) config?

**Comment by gnapse** [comment]
> Why doesn't this just work out-of-the-box like other "npm @types" packages

There are differences with regular packages. For starters a regular package you'll most likely import explicitly what you need from it in the modules you are using it. Custom jest matches OTOH are not imported in the modules you use it, but in a central location, and they also are not used explicitly from the dependency, but they are injected instead into the custom matchers namespace provided by whatever `expect(...)` returns.

That being said, importing jest-dom from the file configured in jest's `setupFilesAfterEnv` should work out of the box. I can't say why it isn't working in your case without having a reproducible example. Can you reproduce this in a minimal repo? (ideally not created with CRA because it is mostly certain that it'll work in CRA out-of-the-box, but that also is an example of how it works, in case you want to compare your setup with a newly created CRA app).

**Comment by xaun** [comment]
@gnapse ah ok. Thanks for the response & info. In the end my problem was I had a mismatched version of "@types/jest" (24.x vs latest of everything else) that was causing a conflict with the Matcher interface 🤦‍♂️ (it was not explicitly complaining about that though, so it was hard to find). Also my project is a components library so a little different project configs than CRA. 

Through this problem I also learnt more about the tsconfig "types" option, originally I had "types": ["node", "react", "jest"], remove all of them I learnt then loads everything in "rootDirs" i.e default @types. This plus fixing my versions meant everything was fine... Until I came across compile issues with [styled-components v5 @types weird react-native dependency](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015). So my final tsconfig is 

```
"types": [
      "node",
      "react",
      "jest",
      "jest-styled-components",
      "@types/testing-library__jest-dom"
    ],
```

with jest config:

```
setupFilesAfterEnv: ['@testing-library/jest-dom/extend-expect', 'jest-styled-components'],
```

Noting that jest-styled-components does a similar thing you mentioned regarding the injected custom matchers.

Just for anyone else maybe working with these packages. Cheers

**Comment by ahmednawaz10p** [comment]
thank you @xaun. adding ` "@types/testing-library__jest-dom"` to `types` in `tsconfig.json` fixed the issue for me

```
"types": [
      "node",
      "jest",
      "@types/testing-library__jest-dom"
    ],
```

**Comment by younessbennaj** [comment]
> add a file named 'jest-dom-d.ts' in src/@types include
> `import '@testing-library/jest-dom/extend-expect';`

thanks !! :)

**Comment by younessbennaj** [comment]
> Maybe this would help:
> 
> ```js
> import '@testing-library/jest-dom/extend-expect';
> ```
> 
> Also add `@types/testing-library__jest-dom` to dependencies of your project.

thanks :)

**Comment by geoyws** [comment]
> 

Only this worked for me. 😃 Thanks man.

**Comment by beeman** [comment]
In my React Native app, this was the fix:

```ts
import '@testing-library/jest-native/extend-expect';
```

**Comment by thiagomini** [comment]
It might be a silly oversight from my side, but if none of the above worked for you, try to first install the types from Definitely Typed:

```bash
npm install --save-dev @types/testing-library__jest-dom
```

This library does not come with types out of the box, and nowhere in the readme docs it reminds you of that. I've created a PR to fix this: https://github.com/testing-library/jest-dom/pull/496
